### ISSUE TITLE
Enhance Qutrub web user interface

### ISSUE THREAD

**Issue by linuxscout** [linuxscout/qutrub#1]
Improve the web interface
improve display

**Comment by mallekbh** [comment]
is this issue still requested ?

**Comment by linuxscout** [comment]
نعم، على الرحب

**Comment by linuxscout** [comment]
- [ ] فعل غير صالح
- [ ] فعل غير صالح بجافا سكريبت
- [ ] حفظ الفعل المصرف في التاريخ
- [ ] جلب حركة الفعل الثلاثي من قاعدة البيانات
- [ ] ملف الإعدادات العامة
- [ ] الأفعال المتكررة
- [ ] write logs
