### ISSUE TITLE
bugs reveled by Watheq Alshowaiter

### ISSUE THREAD

**Issue by linuxscout** [linuxscout/qutrub#21]
مرحبا دكتور طه.. تصميم جميل.. يحتاج قليلا من تعديلات الأخطاء الإملائية..

- [x]  ثانيا، للأسف لم يعمل عندي .. تدوير أيقونة التحميل دون نتيجة، اشتغلت الآن.. يبدو أن الموقع بطيء جدا
- [x]  هناك مشكلة.. عند كتابة الفعل والنقر مباشرة على Enter لا يبحث.. يجب النقر بالماوس عليها .. وهذا غير مريح
- [x] ملاحظة: كتابات البحث لا تظهر في الرابط .. مثال: http://site.com/search=word&something،  .. هذا مفيد في SEO
- [x]  للإتصال مدونتي  غير مرتبة في التذييل
- [x]  دعم `عربايز` واستضافة `شركة الاستضافة` >>  لا داعي لظهور الأيقونة لأنها مشوهة.. يكفي الاسم والرابط
- [x]  بالنسبة لصفحة التحميل، zip => التتحميل كملف وليس كأنه نظام تشغيل

**Comment by linuxscout** [comment]
Fixed
@WatheqAlshowaiter

**Comment by linuxscout** [comment]
اضفنا هذه الميزة
[https://qutrub.arabeyes.org/?verb=كتب](https://qutrub.arabeyes.org/?verb=%D8%A7%D8%B3%D8%AA%D8%A8%D8%B4%D8%B1)

- [x]   ملاحظة: كتابات البحث لا تظهر في الرابط .. مثال: http://site.com/search=word&something، .. هذا مفيد في SEO

**Comment by WatheqAlshowaiter** [comment]
<div style="direction: rtl">
عندي المزيد :) 
١- بخصوص وجود اسم الفعل المبحوث عنه في الرابط فالأفضل أن يضاف إليه في 
<title> قطرب | تصريف الفعل كتب</title>
بحيث أن تغير العنوان مفيد في السيو.. إذا بحث أحدهم عن تصريف فعل ما..

٢- تنسيق التذييل في عبارة كل الحقوق محفوظة=> يحتاج إلى تحسين أن يكون ال@ قبل النص من اليسار لأنه معرف أجنبي ثم يفرق بينه وبين جملة الحقوق.. 

٣- في نسخ الجدول ك csv تظهر كمسخ


٣- ما زلت أكتب في خانة البحث ولا تظهر الكلمة في الرابط  أعلاه..

**Comment by linuxscout** [comment]
- [ ]  ) ١- بخصوص وجود اسم الفعل المبحوث عنه في الرابط فالأفضل أن يضاف إليه في <title> قطرب | تصريف الفعل كتب</title> بحيث أن تغير العنوان مفيد في السيو.. إذا بحث أحدهم عن تصريف فعل ما..
- [ ]  ٢- تنسيق التذييل في عبارة كل الحقوق محفوظة=> يحتاج إلى تحسين أن يكون ال@ قبل النص من اليسار لأنه معرف أجنبي ثم يفرق بينه وبين جملة الحقوق..
- [ ]  ٣- في نسخ الجدول ك csv تظهر كمسخ
- [ ]  ٣- ما زلت أكتب في خانة البحث ولا تظهر الكلمة في الرابط أعلاه..

**Comment by linuxscout** [comment]
Fixed, to be updated on webserver

**Comment by WatheqAlshowaiter** [comment]
السلام عليكم دكتور طه .. هناك من سيحول قاموس آية سبل
ayaspell

لكي يضيفه إلى إضافة ال VS Code التي أخبرتك عنه

لكنه قال أنه لا يعرف إذا كان العمل صحيحًا أم لا ..

فأرجو منكم إذا سمح وقتكم بمراجعتك للعمل..

رابط النقاش
https://github.com/streetsidesoftware/cspell-dicts/issues/941
