### ISSUE TITLE
Qutrub website identifies valid future tense of verb but libqutrub does not

### ISSUE THREAD

**Issue by Kentoseth** [linuxscout/qutrub#35]
assalamu 3laykum,

When I try to run this example:

```
import libqutrub.conjugator

verb=u"ضرب"
all = True # all tenses
display_format="HTML"
table = libqutrub.conjugator.conjugate(verb,all,display_format);
print(table)
```

libqutrub will incorrectly identify the future tense of ضرب as يَضْرَبُ

But when I run ضرب on [qutrub website](https://qutrub.arabeyes.org/?verb=%D8%B6%D8%B1%D8%A8) it correctly identifies the future tense from the unvocalized root.

Why does this not work on libqutrub in the same way?

**Comment by linuxscout** [comment]
Salam,

The Qutrub lib don't use a dictionary, It conjugate with given input only, Where the website provides more suitable feature for user,

Th library provides more flexibility, where the site provides more assistance.

The word ضرب used on site isn't a root but a unvocalivzed  verb, it can have many forms like ضرَب، ضرِب، ضرُب.

if the given verb has more then 3 letters, the vocalization form is deduced automatically.
