### ISSUE TITLE
How can I use it with PHP framworks ?

### ISSUE THREAD

**Issue by ziymed** [linuxscout/qutrub#5]
Thanks fot this application,
I need it to use it in PHP application but I am not good in python how to install it local and server how to run it how to get the Json from it 

I am lost i hope someone help i try to search long time but no tutorials no clue?

thanks

**Comment by linuxscout** [comment]
السلام عليكم،
شكرا لك على الاهتمام

الطريقة الأولى
--------------

يمكنك استعمال المكتبة عبر برنامج CGI لتعمل على الخادم
ثم تربطه بالphp

الطريقة الثانية
------------
استعمال قاعدة بيانات الافعال المصرّفة
المتوفرة على
https://sourceforge.net/projects/qutrub/files/conjugatedVerbs/

**Comment by lb308** [comment]
وعليكم السلام ورحمة الله وبركاته
شكرا لك على هذا الجواب. 
سأحاول إستعمال قاعدة البياتات 

شكرا لمجهوداتك وأرجوا أن تحول هذه البرمجيات إلى اللغات الأخرى المشهورة 
Java, PHP, Javascript, 


أود أن تكون هناك شروح بسيطة عن كيفية تنصيب كل  برامجك من بداية التحميل إلى إظهار المخرجات 
جزاكم الله خيرا

**Comment by linuxscout** [comment]
Now, we have a new web site version,
you can call any verb by;
[https://qutrub.arabeyes.org/?verb=كتب](https://qutrub.arabeyes.org/?verb=كتب)
