### ISSUE TITLE
خطأ 404 عند زيارة صفحة المشروع tahadz.com/qutrub

### ISSUE THREAD

**Issue by Fcmam5** [linuxscout/qutrub#6]
السلام عليكم ورحمة الله وبركاته. من فضلك أستاذ، هناك خطأ في رابط المشروع 
```
# README.md
| Website | [tahadz.com/qutrub](tahadz.com/qutrub) |
```
يعطي صفحة خطأ 404. بالمناسبة، هل يمكنني المساعدة بأي شيء؟ من تطوير الواجهة الأمامية للموقع أو العمل على مهام بالجافاسكريبت؟ سيسرّني ذلك، سواء في هذا المشروع أو في غيره

**Comment by linuxscout** [comment]
Thanks, 
I fixed it.

**Comment by linuxscout** [comment]
يمكنك مساعدتنا في تحسين واحهة مشكال من أجل أن تتوافق مع الجوال
