### ISSUE TITLE
Conjugate on أوزان الثلاثي المزيد فيه

### ISSUE THREAD

**Issue by veeshi** [linuxscout/qutrub#8]
السلام عليكم ورحمة الله وبركاته،

It would be useful if we could put a فعل or حروف أصلية on a وزن from أوزان المزيد فيه

جزاكم الله خيراً وأحسن الجزاء

**Comment by linuxscout** [comment]
وعليكم السلام
بخصوص الفكرة، هي جميلة،

يمكن الحصول عليها من بنرامج صرف للاشتقاق
أما قطرب فيهتم فقط بالتصريف وليس الاشتقاق
لكن يمكن التفكير في عملها كمساعدة للمستخدم

رابط برنامج صرف
https://sourceforge.net/projects/sarf/

**Comment by veeshi** [comment]
شكرا أخي،

أفهم، سأستنسخها في بيثون بإذن الله تعالى
